using Content.Client.Stylesheets;
using Content.Shared._NF.Bank;
using Content.Shared._NF.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Player;

namespace Content.Client._NF.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentListEntry : Control
{
    public event Action<BountyContract>? OnRemoveButtonPressed;

    public BountyContractUiFragmentListEntry(BountyContract contract, bool canRemoveContracts)
    {
        RobustXamlLoader.Load(this);

        // bounty name and title
        if (string.IsNullOrWhiteSpace(contract.Title))
        {
            // title is empty, so use Name as title and hide redundant name
            BountyTitle.Text = contract.Name;
            BountyName.Visible = false;
            BountyContact.HorizontalAlignment = HAlignment.Left;
            InactiveIndicatorTitle.Visible = !contract.AuthorIsActive;
            InactiveIndicatorName.Visible = false;
        }
        else
        {
            BountyTitle.Text = contract.Title;
            BountyName.Visible = true;
            BountyName.Text = contract.Name;
            BountyContact.HorizontalAlignment = HAlignment.Right;
            InactiveIndicatorTitle.Visible = false;
            InactiveIndicatorName.Visible = !contract.AuthorIsActive;
        }

        if (string.IsNullOrWhiteSpace(contract.Contact))
        {
            BountyContact.Visible = false;
        }
        else
        {
            BountyContact.Visible = true;
            BountyContact.Text = Loc.GetString("bounty-contracts-ui-list-contact", ("contact", contract.Contact));
        }

        // vessel
        if (string.IsNullOrEmpty(contract.Vessel) || contract.Vessel == Loc.GetString("bounty-contracts-ui-create-vessel-unknown"))
            BountyVessel.Visible = false;
        else
            BountyVessel.Text = Loc.GetString("bounty-contracts-ui-list-vessel", ("vessel", contract.Vessel));

        // bounty title
        if (string.IsNullOrWhiteSpace(contract.Title))
            BountyTitle.Text = contract.Name;
        else
            BountyTitle.Text = contract.Title;

        // bounty description
        if (string.IsNullOrWhiteSpace(contract.Description))
            BountyDescription.Visible = false;
        else
            BountyDescription.SetMessage(contract.Description);

        // time - display in minutes if less than 90min, hours otherwise
        var timeSinceCreated = DateTime.Now - contract.Created;
        BountyTime.Text = timeSinceCreated.TotalMinutes switch
        {
            < 2 => Loc.GetString("bounty-contracts-ui-list-time-recent"),
            >= 2 and < 90 => Loc.GetString("bounty-contracts-ui-list-time-min", ("mins", (int)timeSinceCreated.TotalMinutes)),
            _ => Loc.GetString("bounty-contracts-ui-list-time-hr", ("hrs", (int)timeSinceCreated.TotalHours))
        };
        BountyTime.AddStyleClass(StyleBase.StyleClassItalic);

        // author
        string author = contract.Author ?? "";
        if (string.IsNullOrWhiteSpace(contract.Author))
            author = Loc.GetString("bounty-contracts-ui-list-unknown-author");

        BountyAuthor.Text = Loc.GetString("bounty-contracts-ui-list-author", ("author", author));
        BountyAuthor.Visible = canRemoveContracts;

        // bounty reward
        if (contract.Reward == 0)
        {
            BountyReward.Visible = false;
        }
        else
        {
            BountyReward.Text = BankSystemExtensions.ToSpesoString(contract.Reward);
            BountyReward.Visible = true;
        }

        // remove button
        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke(contract);
        RemoveButton.Visible = canRemoveContracts;

        // Get category
        var meta = SharedBountyContractSystem.CategoriesMeta[contract.Category];
        BountyPanel.ModulateSelfOverride = meta.UiColor;

        var category = Loc.GetString("bounty-contracts-ui-list-category", ("category", Loc.GetString(meta.Name)));
        BountyCategory.Text = category;
    }
}
